# Generated by Django 5.2.3 on 2025-06-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_certification', '0001_initial'),
        ('employee_profile', '0003_remove_user_id_alter_user_id_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='employee_profile.user'),
        ),
    ]
