# Generated by Django 5.2.3 on 2025-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_certification', '0002_alter_certification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
