# Generated by Django 5.2.3 on 2025-06-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_certification', '0004_alter_certification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certification_documents/'),
        ),
    ]
