# Generated by Django 5.2.3 on 2025-06-23 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_career_history', '0001_initial'),
        ('employee_profile', '0003_remove_user_id_alter_user_id_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='careerhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_histories', to='employee_profile.user'),
        ),
    ]
