# Generated by Django 5.2.3 on 2025-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_career_history', '0002_alter_careerhistory_id_alter_careerhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
