# Generated by Django 5.2.3 on 2025-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_career_history', '0003_alter_careerhistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerhistory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/employee_career_history/'),
        ),
    ]
