# Generated by Django 5.2.3 on 2025-06-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_career_history', '0004_careerhistory_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerhistory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='career_history_documents/'),
        ),
    ]
