# Generated by Django 5.2.3 on 2025-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_contract_history', '0002_remove_contracthistory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracthistory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contract_history_documents/'),
        ),
    ]
