# Generated by Django 5.2.3 on 2025-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_contract_history', '0003_alter_contracthistory_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracthistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='contract_number',
            field=models.CharField(max_length=100),
        ),
    ]
