# Generated by Django 5.2.3 on 2025-06-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('day_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_level', models.CharField(max_length=50)),
                ('employment_status', models.CharField(max_length=50)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
