# Generated by Django 5.2.3 on 2025-06-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Tanpa Nama', max_length=100),
            preserve_default=False,
        ),
    ]
