# Generated by Django 5.2.3 on 2025-06-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_employee',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
